// JScript 파일
document.write('')
document.write('<div id="divLoading" style="display:block">')
document.write('	<center>')
document.write('	<table border="0" cellpadding="0" cellspacing="0" width="100%" height="100%" style="background-color: #FFFFFF">')
document.write('	<tr>')
document.write('		<td valign="middle" align="center">')
document.write('		<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0" width="150" height="60" align="middle" ID="Shockwaveflash1">')
document.write('			<param name="movie" value="Images/loading2.swf">')
document.write('			<param name="quality" value="high">')
document.write('			<param name=wmode value=transparent>')
document.write('			<embed src="Images/loading2.swf" width="150" height="60" align="middle" quality="high" pluginspage="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash"></embed>')
document.write('		</object>')
document.write('		</td>')
document.write('	</tr>')
document.write('	</table>')
document.write('	</center>')
document.write('</div>')
