/*******************************************************************************
' SPLTransfer.vb
'
' Copyright (c) 2007 by Miracom,Inc.
' All rights reserved.
'
' Generated by DevTool XMLGen 1.0
'
' Created at 2008-05-21 14:02:20
'
' Author : Miracom. R&D.
' Description : DevTool Xml Generator Version 1.0
'******************************************************************************/

using System;
using com.miracom.transceiverx.message.former;
using Miracom.SmartWeb.FWX;

namespace Miracom.SmartWeb
{
    public abstract class SPLTransfer
    {
        
        public abstract void SPL_View_Lot_List(SPL_View_Lot_List_In_Tag View_Lot_List_In, ref SPL_View_Lot_List_Out_Tag View_Lot_List_Out);
        public void recv_SPL_View_Lot_List(string sRequest, ref string sReply)
        {
            byte[] outByt = FwxCmnFunction.UnPackMessage(sRequest);
            StreamTransformer former = new StreamTransformerImpl(outByt);
            SPL_View_Lot_List_In_Tag View_Lot_List_In = new SPL_View_Lot_List_In_Tag();
            SPL_View_Lot_List_Out_Tag View_Lot_List_Out = new SPL_View_Lot_List_Out_Tag();

            SPLType.transform_SPL_View_Lot_List_In_Tag(former, ref View_Lot_List_In);
            SPL_View_Lot_List(View_Lot_List_In, ref View_Lot_List_Out); /* Call User Procedure */
            
            former = new StreamTransformerImpl();
            SPLType.serialize_SPL_View_Lot_List_Out_Tag(former, View_Lot_List_Out);

            sReply = FwxCmnFunction.PackMessage(former.getBytes());
        }

        public abstract void SPL_View_Lot_List0(SPL_View_Lot_List0_In_Tag View_Lot_List_In, ref SPL_View_Lot_List0_Out_Tag View_Lot_List_Out);
        public void recv_SPL_View_Lot_List0(string sRequest, ref string sReply)
        {
            byte[] outByt = FwxCmnFunction.UnPackMessage(sRequest);
            StreamTransformer former = new StreamTransformerImpl(outByt);
            SPL_View_Lot_List0_In_Tag View_Lot_List_In = new SPL_View_Lot_List0_In_Tag();
            SPL_View_Lot_List0_Out_Tag View_Lot_List_Out = new SPL_View_Lot_List0_Out_Tag();

            SPLType.transform_SPL_View_Lot_List0_In_Tag(former, ref View_Lot_List_In);
            SPL_View_Lot_List0(View_Lot_List_In, ref View_Lot_List_Out); /* Call User Procedure */
            
            former = new StreamTransformerImpl();
            SPLType.serialize_SPL_View_Lot_List0_Out_Tag(former, View_Lot_List_Out);

            sReply = FwxCmnFunction.PackMessage(former.getBytes());
        }

    }
}

