/*******************************************************************************
' FMBSkeleton.vb
'
' Copyright (c) 2007 by Miracom,Inc.
' All rights reserved.
'
' Generated by DevTool XMLGen 1.0
'
' Created at 2008-05-29 16:13:41
'
' Author : Miracom. R&D.
' Description : DevTool Xml Generator Version 1.0
'******************************************************************************/

using System;

namespace Miracom.SmartWeb.RO
{
    public partial class FMBTransferImp : FMBTransfer
    {
        

        public override void FMB_View_UDR_Group_List(FMB_View_UDR_Group_List_In_Tag View_UDR_Group_List_In, ref FMB_View_UDR_Group_List_Out_Tag View_UDR_Group_List_Out)
        {
            try
            {
                // TODO : User code

            }
            catch(Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }




        public override void FMB_View_UDR_Resource_List(FMB_View_UDR_Resource_List_In_Tag View_UDR_Resource_List_In, ref FMB_View_UDR_Resource_List_Out_Tag View_UDR_Resource_List_Out)
        {
            try
            {
                // TODO : User code

            }
            catch(Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }

        public override void FMB_Update_UDR_Group(FMB_Update_UDR_Group_In_Tag Update_UDR_Group_In, ref FMB_Cmn_Out_Tag Cmn_Out)
        {
            try
            {
                // TODO : User code

            }
            catch(Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }



        public override void FMB_Update_LayOut(FMB_Update_LayOut_In_Tag Update_LayOut_In, ref FMB_Cmn_Out_Tag Cmn_Out)
        {
            try
            {
                // TODO : User code

            }
            catch(Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }

        public override void FMB_View_Resource(FMB_View_Resource_In_Tag View_Resource_In, ref FMB_View_Resource_Out_Tag View_Resource_Out)
        {
            try
            {
                // TODO : User code

            }
            catch(Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }

        public override void FMB_View_UDR_Resource(FMB_View_UDR_Resource_In_Tag View_UDR_Resource_In, ref FMB_View_UDR_Resource_Out_Tag View_UDR_Resource_Out)
        {
            try
            {
                // TODO : User code

            }
            catch(Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }

        public override void FMB_View_Resource_History(FMB_View_Resource_History_In_Tag View_Resource_History_In, ref FMB_View_Resource_History_Out_Tag View_Resource_History_Out)
        {
            try
            {
                // TODO : User code

            }
            catch(Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }

        public override void FMB_View_LotByRes_List(FMB_View_LotByRes_List_In_Tag View_LotByRes_List_In, ref FMB_View_LotByRes_List_Out_Tag View_LotByRes_List_Out)
        {
            try
            {
                // TODO : User code

            }
            catch(Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }

        public override void FMB_View_Lot_List_Detail(FMB_View_Lot_List_Detail_In_Tag View_Lot_List_Detail_In, ref FMB_View_Lot_List_Detail_Out_Tag View_Lot_List_Detail_Out)
        {
            try
            {
                // TODO : User code

            }
            catch(Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }

        public override void FMB_View_Factory(FMB_View_Factory_In_Tag View_Factory_In, ref FMB_View_Factory_Out_Tag View_Factory_Out)
        {
            try
            {
                // TODO : User code

            }
            catch(Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }

        public override void FMB_View_Factory_List(FMB_View_Factory_List_In_Tag View_Factory_List_In, ref FMB_View_Factory_List_Out_Tag View_Factory_List_Out)
        {
            try
            {
                // TODO : User code

            }
            catch (Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }

        public override void FMB_View_Factory_Cmf_Item(FMB_View_Factory_Cmf_Item_In_Tag View_Factory_Cmf_Item_In, ref FMB_View_Factory_Cmf_Item_Out_Tag View_Factory_Cmf_Item_Out)
        {
            try
            {
                // TODO : User code

            }
            catch(Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }

        public override void FMB_View_Material_List(FMB_View_Material_List_In_Tag View_Material_List_In, ref FMB_View_Material_List_Out_Tag View_Material_List_Out)
        {
            try
            {
                // TODO : User code

            }
            catch(Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }

        public override void FMB_View_Flow_List(FMB_View_Flow_List_In_Tag View_Flow_List_In, ref FMB_View_Flow_List_Out_Tag View_Flow_List_Out)
        {
            try
            {
                // TODO : User code

            }
            catch(Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }

        public override void FMB_View_Operation_List(FMB_View_Operation_List_In_Tag View_Operation_List_In, ref FMB_View_Operation_List_Out_Tag View_Operation_List_Out)
        {
            try
            {
                // TODO : User code

            }
            catch(Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }

        public override void FMB_View_ResEvent_List(FMB_View_ResEvent_List_In_Tag View_ResEvent_List_In, ref FMB_View_ResEvent_List_Out_Tag View_ResEvent_List_Out)
        {
            try
            {
                // TODO : User code

            }
            catch(Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }

        public override void FMB_View_ResLot_List(FMB_View_ResLot_List_In_Tag View_ResLot_List_In, ref FMB_View_ResLot_List_Out_Tag View_ResLot_List_Out)
        {
            try
            {
                // TODO : User code

            }
            catch(Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }

        public override void FMB_View_Data_List(FMB_View_Data_List_In_Tag View_Data_List_In, ref FMB_View_Data_List_Out_Tag View_Data_List_Out)
        {
            try
            {
                // TODO : User code

            }
            catch(Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }

        public override void FMB_Moving_by_Force(FMB_Moving_by_Force_In_Tag Moving_by_Force_In, ref FMB_Cmn_Out_Tag Cmn_Out)
        {
            try
            {
                // TODO : User code

            }
            catch(Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }

        public override void FMB_Exist_Control(FMB_Exist_Control_In_Tag Exist_Control_In, ref FMB_Exist_Control_Out_Tag Exist_Control_Out)
        {
            try
            {
                // TODO : User code

            }
            catch(Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }

        public override void FMB_View_User_List(FMB_View_User_List_In_Tag View_User_List_In, ref FMB_View_User_List_Out_Tag View_User_List_Out)
        {
            try
            {
                // TODO : User code

            }
            catch(Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }

        public override void FMB_View_SecGrp_List(FMB_View_SecGrp_List_In_Tag View_SecGrp_List_In, ref FMB_View_SecGrp_List_Out_Tag View_SecGrp_List_Out)
        {
            try
            {
                // TODO : User code

            }
            catch(Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }

        public override void FMB_View_ResDetail_List(FMB_View_ResDetail_In_Tag View_ResDetail_In, ref FMB_View_ResDetail_Out_Tag View_ResDetail_Out)
        {
            try
            {
                // TODO : User code

            }
            catch(Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }

        public override void FMB_Login(FMB_Login_In_Tag Login_In, ref FMB_Login_Out_Tag Login_Out)
        {
            try
            {
                // TODO : User code

            }
            catch(Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }

        public override void FMB_Resource_Event(FMB_Resource_Event_In_Tag Resource_Event_In, ref FMB_Resource_Event_Out_Tag Resource_Event_Out)
        {
            try
            {
                // TODO : User code

            }
            catch(Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }

        public override void FMB_Collect_Res_Data(FMB_Resource_Event_In_Tag Resource_Event_In, ref FMB_Resource_Event_Out_Tag Resource_Event_Out)
        {
            try
            {
                // TODO : User code

            }
            catch(Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }

        public override void FMB_Find_Col_Set_Version(FMB_Find_Col_Set_Version_In_Tag Find_Col_Set_Version_In, ref FMB_Find_Col_Set_Version_Out_Tag Find_Col_Set_Version_Out)
        {
            try
            {
                // TODO : User code

            }
            catch(Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }

        public override void FMB_View_Attach_Character_List(FMB_View_Attach_Character_List_In_Tag View_Attach_Character_List_In, ref FMB_View_Attach_Character_List_Out_Tag View_Attach_Character_List_Out)
        {
            try
            {
                // TODO : User code

            }
            catch(Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }

        public override void FMB_View_Default_Unit_List(FMB_View_Default_Unit_List_In_Tag View_Default_Unit_List_In, ref FMB_View_Default_Unit_List_Out_Tag View_Default_Unit_List_Out)
        {
            try
            {
                // TODO : User code

            }
            catch(Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }

        public override void FMB_View_Event(FMB_View_Event_In_Tag View_Event_In, ref FMB_View_Event_Out_Tag View_Event_Out)
        {
            try
            {
                // TODO : User code

            }
            catch(Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }

        public override void FMB_Update_Environment(FMB_Update_Environment_In_Tag Update_Environment_In, ref FMB_Cmn_Out_Tag Cmn_Out)
        {
            try
            {
                // TODO : User code

            }
            catch(Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }

        public override void FMB_View_Environment(FMB_View_Environment_In_Tag View_Environment_In, ref FMB_View_Environment_Out_Tag View_Environment_Out)
        {
            try
            {
                // TODO : User code

            }
            catch(Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }

        public override void FMB_View_Environment_List(FMB_View_Environment_List_In_Tag View_Environment_List_In, ref FMB_View_Environment_List_Out_Tag View_Environment_List_Out)
        {
            try
            {
                // TODO : User code

            }
            catch(Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }

        public override void FMB_Update_Event_Color(FMB_Update_Event_Color_In_Tag Update_Event_Color_In, ref FMB_Cmn_Out_Tag Cmn_Out)
        {
            try
            {
                // TODO : User code

            }
            catch(Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }

        public override void FMB_View_Event_Color_List(FMB_View_Event_Color_List_In_Tag View_Event_Color_List_In, ref FMB_View_Event_Color_List_Out_Tag View_Event_Color_List_Out)
        {
            try
            {
                // TODO : User code

            }
            catch(Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }

        public override void FMB_View_Event_Color(FMB_View_Event_Color_In_Tag View_Event_Color_In, ref FMB_View_Event_Color_Out_Tag View_Event_Color_Out)
        {
            try
            {
                // TODO : User code

            }
            catch(Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }

        public override void FMB_Update_Resource_Image(FMB_Update_Resource_Image_In_Tag Update_Resource_Image_In, ref FMB_Cmn_Out_Tag Cmn_Out)
        {
            try
            {
                // TODO : User code

            }
            catch(Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }

        public override void FMB_View_Resource_Image_List(FMB_View_Resource_Image_List_In_Tag View_Resource_Image_List_In, ref FMB_View_Resource_Image_List_Out_Tag View_Resource_Image_List_Out)
        {
            try
            {
                // TODO : User code

            }
            catch(Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }

        public override void FMB_Update_ResLoc_List(FMB_Update_ResLoc_List_In_Tag Update_ResLoc_List_In, ref FMB_Cmn_Out_Tag Cmn_Out)
        {
            try
            {
                // TODO : User code

            }
            catch(Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }

        public override void FMB_Update_UDRLoc_List(FMB_Update_UDRLoc_List_In_Tag Update_UDRLoc_List_In, ref FMB_Cmn_Out_Tag Cmn_Out)
        {
            try
            {
                // TODO : User code

            }
            catch(Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }

        public override void FMB_Check_Version(FMB_Check_Version_In_Tag Check_Version_In, ref FMB_Check_Version_Out_Tag Check_Version_Out)
        {
            try
            {
                // TODO : User code

            }
            catch(Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }

        public override void FMB_View_Function_List(FMB_View_Function_List_In_Tag View_Function_List_In, ref FMB_View_Function_List_Out_Tag View_Function_List_Out)
        {
            try
            {
                // TODO : User code

            }
            catch(Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }

        public override void FMB_View_Function_Detail(FMB_View_Function_Detail_In_Tag View_Function_In, ref FMB_View_Function_Detail_Out_Tag View_Function_Out)
        {
            try
            {
                // TODO : User code

            }
            catch(Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }

        public override void FMB_Get_HelpURL(FMB_Get_HelpURL_In_Tag Get_HelpURL_In, ref FMB_Get_HelpURL_Out_Tag Get_HelpURL_Out)
        {
            try
            {
                // TODO : User code

            }
            catch(Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }

        public override void FMB_View_Attach_Character(FMB_View_Attach_Character_In_Tag View_Attach_Character_In, ref FMB_View_Attach_Character_Out_Tag View_Attach_Character_Out)
        {
            try
            {
                // TODO : User code

            }
            catch(Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }

        public override void FMB_Copy_UDR_Group(FMB_Copy_UDR_Group_In_Tag Copy_UDR_Group_In, ref FMB_Cmn_Out_Tag Cmn_Out)
        {
            try
            {
                // TODO : User code

            }
            catch(Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }

        public override void FMB_Update_FMB_Group(FMB_Update_FMB_Group_In_Tag Update_FMB_Group_In, ref FMB_Cmn_Out_Tag Cmn_Out)
        {
            try
            {
                // TODO : User code

            }
            catch(Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }

    
    }
}
